frontend/src/components/users/Users.js
frontend/src/store/actions/index.js
frontend/src/store/configureStore.js
frontend/src/store/reducers.js

Improve code readability, DX by
- creating Action Creator index.js
- changing to get state as argument in mapStateToProps function and declaring which state to use explicitly instead of destructuring state object
- declaring reducer name explicitly to improve readability when combining each reducer
@dreamingblackcat

improve code readability

---

Readme.md
backend/bin/start_test.bat
backend/bin/start_test.sh
backend/conf/config_test.yaml
backend/src/app.py
backend/src/common/config.py
backend/test/test_app.py

- adding test case for whole app.
- testcase with pytest

Kz 13 testcase setup

---

backend/src/app.py
backend/src/controller/api.py
backend/src/models/address.py
backend/src/models/user.py
backend/src/service/user/user_service.py

Call URL: http://localhost:5000/api/v1/user
The following functions are implemented:
1. join the result of user with addresses table
2. instead of address_id show the address in results
3. modify create method (using POST method)
4. delete action (using DELETE method)
5. update action (using PUT method)
6. read action modification (using GET method) (get all)
**some structure of app.py and api.py is changed.
**added new service layer

#6 [user_manage] join user with address, store hashed password, user CRUD

---

backend/docs/address.md
backend/src/controller/address.py
backend/src/models/address.py
backend/src/service/address/address_service.py

Added Addressed Delete and Retrieve All functions and Doc.

Issue #7 Address CRUD 

---

draft_server/sample_data/addresses.json
frontend/src/components/layouts/Sidebar.js

UI mockup done.
added addresses data
added menu items
fixed menu grid 2-8-2 to 1-10-1

Issue #47 UI for address Page

---

Readme.md

Modify readme.md file for windows frontend development setup

#yma-env-modify modify Readme.md for windows user

---

backend/src/controller/address.py
backend/src/controller/api.py
backend/src/controller/attendance.py
backend/src/controller/school.py
backend/src/controller/user.py

1. modify /login endpoint return format 
```
{
"data": {
"access_token": "XXX",
"user": {
"email": "moemoe@gmail.com",
"id": 1,
"username": "MoeMoe"
}
}
}
```
2. Change Error Message format 
```
{
"errors": [
{
"description": "Requested moemoe1@gmail.com is not a registered member",
"error_code": "E0007",
"reason": "Request ERROR"
}
]
}
```

modify login endpoint and error format fixed #33

---

backend/docs/attendance.md
backend/docs/schools.md
backend/docs/transfer.md
backend/src/controller/attendance.py
backend/src/controller/school.py
backend/src/controller/transfer.py

@khinezarthwe it is ready to be reviewed.

Fix issue #66

---

backend/docs/address.md
backend/docs/attendance.md
backend/docs/schools.md
backend/docs/transfer.md
backend/docs/users.md
backend/src/controller/address.py
backend/src/controller/attendance.py
backend/src/controller/school.py
backend/src/controller/transfer.py
backend/src/controller/user.py
backend/src/models/attendance.py
backend/src/models/school.py
backend/src/models/student.py
backend/src/models/transfer.py
backend/src/models/user.py
backend/src/service/address/address_service.py
backend/src/service/attendance/attendance_service.py
backend/src/service/school/school_service.py
backend/src/service/student/student_service.py
backend/src/service/transfer/transfer_service.py
backend/src/service/user/user_service.py

- Adding Pagination for 
- Modify APIs Docs

Kzt pagination issue 20

---

backend/bin/db_seed/thingaha.postman_collection.json
backend/docs/address.md
backend/docs/attendance.md
backend/docs/donation.md
backend/docs/error.md
backend/docs/extrafunds.md
backend/docs/schools.md
backend/docs/student.md
backend/docs/transfer.md
backend/docs/users.md
backend/src/controller/user.py
backend/src/models/user.py
backend/src/service/user/user_service.py
backend/test/test_app.py

`api/v1/users/search?query=XXX`
`api/v1/users?role=XXXX`
`api/v1/users?country=XXXX`

#kzt-user-search-28 issue fixed#28 for user search query and filter

---

backend/src/controller/school.py
backend/src/controller/student.py
backend/src/controller/user.py
backend/src/models/school.py
backend/src/models/student.py
backend/src/models/user.py
backend/src/service/student/student_service.py
backend/src/service/user/user_service.py
backend/test/test_app.py

Added address delete process in
delete_school_by_id
delete_student_by_id
delete_user_by_id

#84 Delete address when delete user, school and student

---

backend/conf/config_docker.yaml
backend/docs/schools.md
backend/src/common/data_schema.py
backend/src/controller/school.py
backend/src/service/address/address_service.py
backend/src/service/school/school_service.py
backend/test/test_app.py
draft_server/index.js
frontend/src/components/schools/SchoolForm.js
frontend/src/components/users/Users.js
frontend/src/store/api/schools.js
frontend/src/store/reducers/schools.js
frontend/src/store/sagas/schools.js
frontend/src/utils/thingahaApiClient.js
frontend/src/utils/updateObjectInArray.js

Includes update to:
- School list
- Add new school
- Edit school
features.

Linking school UI with backend python api

---

backend/bin/db_seed/thingaha.postman_collection 22.45.20.json
backend/docs/users.md
backend/src/app.py
backend/src/controller/user.py
backend/src/models/attendance.py
backend/src/models/user.py
backend/src/service/user/user_service.py

Change password

---

Readme.md
frontend/package.json
frontend/yarn.lock

Readme update and package json update for installation

Readme update

---

backend/bin/db_seed/thingaha.postman_collection.json
backend/docs/users.md
backend/src/controller/api.py

change login params
```json
{
"email_or_username": "moemoe@gmail.com",
"password": "123"
}
```

login user bug fixed #108

---

backend/docs/users.md
backend/src/common/data_schema.py
backend/src/controller/user.py
backend/src/service/user/user_service.py
backend/test/test_app.py
backend/test/test_donator.py
backend/test/test_sub_admin.py

full admin user can reset the password.
Input Sample:
```json
{
"user_id": 1,
"password": "1234"
}
```
Output Sample:
```json
{
"status": true
}
```

fixed #110 admin user can reset the password

---

backend/docs/student.md
backend/src/controller/student.py
backend/src/models/student.py
backend/src/service/student/student_service.py
backend/src/service/user/user_service.py
backend/test/test_app.py
backend/test/test_donator.py
backend/test/test_sub_admin.py

- Retrieve students info by name, father_name, mother_name or parents_occupation

Search students

---

frontend/src/components/donations/DonationCard.js

correct month's short form and margin

Yma 127 donation UI

---

backend/src/controller/user.py
backend/src/models/user.py
frontend/src/components/addresses/Addresses.js
frontend/src/components/addresses/AddressesCard.js
frontend/src/components/common/ThingahaName.js
frontend/src/components/dashboard/CurrentMonthDonations.js
frontend/src/components/dashboard/DonatorCard.js
frontend/src/components/donations/DonationCard.js
frontend/src/components/donations/DonationDetails.js
frontend/src/components/schools/SchoolCard.js
frontend/src/components/schools/Schools.js
frontend/src/components/students/StudentCard.js
frontend/src/components/students/StudentDetails.js
frontend/src/components/students/Students.js
frontend/src/components/users/UserCard.js
frontend/src/components/users/UserForm.js
frontend/src/components/users/Users.js
frontend/src/store/api/users.js
frontend/src/store/reducers/users.js
frontend/src/store/sagas/addresses.js
frontend/src/store/sagas/users.js
frontend/src/styles/global.js
frontend/src/styles/palette.js

bba7b71 (dreamingblackcat, 14 seconds ago)
Only show contact info when there is one in Schools page
1a75050 (dreamingblackcat, 26 seconds ago)
Add numbering and total count in Donator dashboard
f07580d (dreamingblackcat, 19 minutes ago)
Extract common text element class for names into ThingahaName component for
reuse
9eae9c2 (dreamingblackcat, 38 minutes ago)
Make primary font sizes smaller and cleaner across donation, school and
student pages
3934fb5 (dreamingblackcat, 38 minutes ago)
Improve users UI
512daef (dreamingblackcat, 2 hours ago)
Update address page being broken due to type name differences
2ceae44 (dreamingblackcat, 3 hours ago)
Add pagination to the users page

Miscellaneous bug fixes and changes in Frontend

---

backend/bin/db_seed/thingaha.postman_collection.json
backend/docs/donation.md
backend/src/controller/donation.py
backend/src/models/donation.py
backend/src/service/donation/donation_service.py
backend/test/test_app.py
backend/test/test_donator.py
backend/test/test_sub_admin.py

URL:  [GET] 
```
http://xxx/api/v1/donator_donations
http://xxx/api/v1/donator_donations?year=2017&month=june
```
Response example:
```
{
"data": {
"current_page": 1,
"donations": [
{
"attendance_id": 25,
"id": 328,
"jpy_amount": 0.0,
"mmk_amount": 50000.0,
"month": "june",
"paid_at": null,
"status": "pending",
"student": {
"address": {
"district": "မအူပင်ခရိုင်",
"division": "ayeyarwady",
"id": 96,
"street_address": "ဘားလင်းကျေးရွာ",
"township": "ညောင်တုန်းမြို့နယ်"
},
"birth_date": "2002-03-03",
"deactivated_at": "31-03-2019",
"father_name": "ဦးစိုးဝင်း",
"id": 25,
"mother_name": "ဒေါ်သိန်းကြည်",
"name": "မအေးအေးခိုင်",
"parents_occupation": "ကျပန်း လက်လုပ်လက်စား",
"photo": ""
},
"transfer_id": null,
"user": {
"address": {
"district": "မအူပင်ခရိုင်",
"division": "ayeyarwady",
"id": 25, …
```

#136 adding donator's donation API

---

frontend/src/components/addresses/AddressList.js
frontend/src/components/addresses/Addresses.js
frontend/src/components/addresses/AddressesCard.js
frontend/src/store/actions/addresses.js
frontend/src/store/api/addresses.js
frontend/src/store/reducers/addresses.js
frontend/src/store/sagas/addresses.js

-fixed-
add pagination to address page.
show addresses by types.
add item no. in address list

Issue #134 Address Page Bug Fix

---

frontend/src/App.js
frontend/src/components/extraFunds/ExtraFundCurrentAmount.js
frontend/src/components/extraFunds/ExtraFundForTransfer.js
frontend/src/components/transfers/TransferCard.js
frontend/src/components/transfers/TransferDetails.js
frontend/src/store/actions/transfers.js
frontend/src/store/api/transfers.js
frontend/src/store/reducers/transfers.js
frontend/src/store/saga.js
frontend/src/store/sagas/transfers.js

Issue #42 Transfer Page

---

frontend/src/components/attendances/AttendanceCard.js
frontend/src/components/attendances/Attendances.js

removed Donator item
added Enrolled Date item
fixed Grade and Schools data
fixed UI.

Issue #159 attendance bug

---

backend/src/common/error.py
backend/src/controller/api.py
backend/src/controller/user.py

Login in user can edit their details

#146 users can edit their details

---

backend/docs/attendance.md
backend/src/controller/attendance.py
backend/src/models/attendance.py
backend/src/service/attendance/attendance_service.py

Add search by grade, year and student name support to attendances

---

frontend/src/components/students/Students.js
frontend/src/store/actions/students.js
frontend/src/store/api/students.js
frontend/src/store/saga.js
frontend/src/store/sagas/students.js

This implements #177 . Now, you can search students via keyword search.

Integrate student search functionality with backend. Implements #177
